install.packages(
  c(
      'ggplot2',
      'png',
      'extrafont',
      'knitr',
      'rmarkdown',
      'shiny',
      'shinydashboard',
      'tinytex',
      'here',
      'RCurl',
      'devtools',
      'remotes',
      'readr',
      'DT',
      'stringr',
      'fs',
      'lubridate',
      'dplyr',
      'purrr',
      'janitor'
  ), repo = 'https://cloud.r-project.org/')
